### PR TITLE
Amina/Upgrade model new signup

### PR DESCRIPTION
**Pull request by amina-deriv**

### CODE REVIEW

**Comment by ali-hosseini-fs** [comment]
image

**Comment by ali-hosseini-fs** [comment]
Also check margin top/bottom of the `You can add the other account later.` text.

**Comment by amina-deriv** [comment]
> Also check margin top/bottom of the `You can add the other account later.` text.

[](ur
Screen Shot 2021-11-01 at 9 58 42 AM **(2)**
l)
@ali-hosseini-fs  CSS updated. Could you please check?

**Comment by ali-hosseini-fs** [comment]
> > Also check margin top/bottom of the `You can add the other account later.` text.
> 
> Screen Shot 2021-11-01 at 9 58 42 AM (2)
> 
> @ali-hosseini-fs CSS updated. Could you please check?

@amina-deriv  The red section (  `You are currently using this in demo` ) should have border-radius and also it's not completely center

**Pull request merged**
